---
- apt_repository: repo="ppa:webupd8team/java"

- name: Add Elasticsearch key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add Elasticseach source list file
  copy: src=elasticsearch.list dest=/etc/apt/sources.list.d/elasticsearch.list

- name: Accept oracle license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

# These are separated out, since they each take a long time:
- name: Java8 Installer
  apt: name=oracle-java8-installer update_cache=yes

- name: Java8 Set Default
  apt: name=oracle-java8-set-default

- name: Elasticsearch
  apt: name=elasticsearch=1.4.4
  notify: Start Elasticsearch

- name: Elasticsearch on boot
  shell: update-rc.d elasticsearch defaults 95 10

- name: Bind to Elasticsearch to localhost
  lineinfile: dest=/etc/elasticsearch/elasticsearch.yml regexp='^#*network.bind_host:' line='network.host{{':'}} "127.0.0.1"'
  notify: Restart Elasticsearch
