---

- name: Log out password
  debug: msg="Root password is {{ mongo.root_admin_password }}"

- name: Import the public key used by the package management system.
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10

- name: Check if running on systemd
  command: cat /proc/1/cmdline
  register: systemd
  changed_when: false
  always_run: yes # side-effect free, so it can be run in check-mode as well

- name: Add systemd configuration if present
  copy: src=mongodb.service dest=/lib/systemd/system/mongodb.service owner=root group=root mode=0640
  when: "'systemd' in systemd.stdout"

- name: Add symlink for systemd
  file: src=/lib/systemd/system/mongodb.service dest=/etc/systemd/system/multi-user.target.wants/mongodb.service state=link
  when: "'systemd' in systemd.stdout"
  notify: reload systemd

- meta: flush_handlers
  when: "'systemd' in systemd.stdout"

- name: Create a list file for MongoDB.
  template: src=mongodb-org-{{ mongo.version }}.list dest=/etc/apt/sources.list.d/mongodb-org-{{ mongo.version }}.list

- name: Install mongo
  apt: name=mongodb-org update_cache=yes
  async: 1800

- name: Turn off authorization
  set_fact: mongo_auth_enabled="disabled"

- name: Set mongo configuration file
  template: src=mongo.conf dest=/etc/mongod.conf

- name: Install pymongo for any project related mongo
  pip: name=pymongo
  async: 1800

# should be using service module, but it can't find mongod!
- name: Start mongo service
  raw: service mongod start
  sudo: yes
  ignore_errors: yes

- name: create administrative user siteRootAdmin
  mongodb_user:
    database: admin
    name: "{{ mongo.root_admin_name }}"
    password: "{{ mongo.root_admin_password }}"
    # always will update passwords if they differ. on_create will only set the password for newly created users.
    update_password: "on_create"
    roles: "root"

- name: create backup user "backupuser"
  mongodb_user:
    database: admin
    name: "{{ mongo.backup_name }}"
    password: "{{ mongo.backup_password }}"
    # always will update passwords if they differ. on_create will only set the password for newly created users.
    update_password: "on_create"
    roles: "backup,clusterMonitor"

- name: Turn on authorization
  set_fact: mongo_auth_enabled="enabled"

- name: Set mongo configuration file
  template: src=mongo.conf dest=/etc/mongod.conf

- name: Start mongo service
  service: name=mongod state=restarted
  sudo: yes