---

- name: Checking essentials
  apt: name="{{ item }}" state=present
  with_items:
  - libmysqlclient-dev

- name: Install mysql
  apt: pkg="mysql-server"

- name: Install mysql for python
  pip: name=MySQL-python

- name: Bind Localhost
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address\s*=" line="bind-address = 127.0.0.1"
  notify:
    - Start Mysql
